volumes:
  mysql-data:
    driver: local
  mysql-data-test:
    driver: local
  redis-data:
    driver: local

services:
  api:
    build:
      context: ./environment
      dockerfile: Dockerfile
    container_name: travly-api
    depends_on:
      - nginx
      - db
      - redis
    ports:
      - 9000:9000
    volumes:
      - .:/var/www
    networks:
      - travly

  nginx:
    image: nginx:alpine
    container_name: travly-nginx
    ports:
      - 80:80
    volumes:
      - .:/var/www
      - ./environment/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - travly

  db:
    image: mysql
    container_name: travly-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: travly
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: travlydb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - travly

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: travly-phpMyAdmin
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - travly
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    volumes:
      - ./environment/phpmyadmin/apache.conf:/etc/apache2/conf-enabled/custom_apache.conf

  docs:
    image: swaggerapi/swagger-ui:v5.17.14
    container_name: travly-api-documentation
    ports:
      - "300:8080"
    volumes:
      - ./openapi.yml:/tmp/openapi.yml
    environment:
      SWAGGER_JSON: /tmp/openapi.yml

  redis:
    image: redis:latest
    container_name: travly-redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - travly

  mailhog:
    image: mailhog/mailhog
    container_name: 'travly-mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - travly

networks:
  travly:
    driver: bridge
